version: '3'

services:
  node:
    build: ./node
    restart: always
    ports:
      - '5000:5000'
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./react/build:/usr/share/nginx/html
    depends_on:
      - node